// ── Course Data ──────────────────────────────────────────────
const COURSES = [
  // ═══════════════════════ C++ ═══════════════════════
  {
    id: "cpp-1", lang: "C++", level: 1,
    color: "#00599C", bg: "rgba(0,89,156,0.12)", tag: "C++",
    title: "C++ Fundamentals",
    desc: "Master the building blocks of C++ — variables, control flow, functions, arrays, and pointers.",
    topics: ["Variables & Types", "Control Flow", "Functions", "Arrays", "Pointers & References"],
    hours: 30, projects: 5,
    curriculum: [
      "Setting Up Your C++ Environment (GCC / Clang / MSVC)",
      "Hello World & Compilation Pipeline",
      "Variables, Data Types & Type Casting",
      "Operators & Expressions",
      "Conditional Statements (if / else / switch)",
      "Loops: for, while, do-while",
      "Functions: Declaration, Definition & Overloading",
      "Default & Inline Functions",
      "Arrays & C-Strings",
      "Pointers: Basics & Arithmetic",
      "References vs Pointers",
      "Dynamic Memory: new / delete",
      "Header Files & Multi-File Projects",
      "Debugging with GDB / LLDB",
      "Final Project: Console-Based Student Database"
    ]
  },
  {
    id: "cpp-2", lang: "C++", level: 2,
    color: "#00599C", bg: "rgba(0,89,156,0.12)", tag: "C++",
    title: "Object-Oriented C++",
    desc: "Deep dive into classes, inheritance, polymorphism, and operator overloading.",
    topics: ["Classes", "Inheritance", "Polymorphism", "Operator Overloading", "RAII"],
    hours: 35, projects: 6,
    curriculum: [
      "Structs vs Classes",
      "Constructors, Destructors & Rule of Three",
      "Access Specifiers & Encapsulation",
      "this Pointer & Const Member Functions",
      "Static Members & Friend Functions",
      "Operator Overloading (+, <<, ==, [])",
      "Single & Multiple Inheritance",
      "Virtual Functions & VTable",
      "Abstract Classes & Pure Virtual Functions",
      "Runtime Polymorphism Patterns",
      "RAII & Resource Management",
      "Copy vs Move Semantics Intro",
      "Namespaces & Scope Resolution",
      "Exception Handling: try / catch / throw",
      "Final Project: Banking System with Polymorphism"
    ]
  },
  {
    id: "cpp-3", lang: "C++", level: 3,
    color: "#00599C", bg: "rgba(0,89,156,0.12)", tag: "C++",
    title: "STL & Templates",
    desc: "Harness the Standard Template Library and write generic, reusable code with templates.",
    topics: ["Templates", "STL Containers", "Iterators", "Algorithms", "Smart Pointers"],
    hours: 35, projects: 5,
    curriculum: [
      "Function Templates & Type Deduction",
      "Class Templates & Specialization",
      "Variadic Templates Basics",
      "STL Containers: vector, list, deque",
      "Associative Containers: map, set, unordered_map",
      "Iterators: Categories & Custom Iterators",
      "STL Algorithms: sort, find, transform, accumulate",
      "Lambda Expressions with STL",
      "Smart Pointers: unique_ptr, shared_ptr, weak_ptr",
      "std::optional, std::variant, std::any",
      "String Streams & File I/O",
      "Regular Expressions in C++",
      "Custom Allocators Intro",
      "Benchmarking with <chrono>",
      "Final Project: Generic Data Pipeline Library"
    ]
  },
  {
    id: "cpp-4", lang: "C++", level: 4,
    color: "#00599C", bg: "rgba(0,89,156,0.12)", tag: "C++",
    title: "Modern C++ (17/20)",
    desc: "Explore cutting-edge features — structured bindings, concepts, ranges, coroutines, and modules.",
    topics: ["C++17 Features", "C++20 Concepts", "Ranges", "Coroutines", "Modules"],
    hours: 40, projects: 5,
    curriculum: [
      "Structured Bindings & if-init",
      "std::filesystem Library",
      "std::string_view & Performance",
      "Fold Expressions",
      "constexpr if & Compile-Time Programming",
      "C++20 Concepts & Constraints",
      "Ranges Library: Views & Adaptors",
      "Three-Way Comparison (Spaceship Operator)",
      "Coroutines: co_await, co_yield, co_return",
      "C++20 Modules Basics",
      "Designated Initializers",
      "Calendar & Timezone (<chrono> C++20)",
      "std::format — Modern Formatting",
      "Compile-Time Reflection Preview",
      "Final Project: Async Task Scheduler with Coroutines"
    ]
  },
  {
    id: "cpp-5", lang: "C++", level: 5,
    color: "#00599C", bg: "rgba(0,89,156,0.12)", tag: "C++",
    title: "Systems & Performance",
    desc: "Low-level systems programming — multithreading, memory models, networking, and optimization.",
    topics: ["Multithreading", "Memory Model", "Networking", "Profiling", "OS Internals"],
    hours: 45, projects: 4,
    curriculum: [
      "Threads: std::thread & std::jthread",
      "Mutexes, Locks & Condition Variables",
      "Atomic Operations & Memory Ordering",
      "Lock-Free Data Structures",
      "Thread Pools & Task Queues",
      "POSIX Sockets & Networking Basics",
      "Asynchronous I/O with epoll / io_uring",
      "Memory Layout: Stack, Heap, Data Segments",
      "Cache-Friendly Programming",
      "Profile-Guided Optimization (PGO)",
      "Valgrind, ASan & TSan",
      "Building Shared & Static Libraries",
      "CMake Advanced: Targets & Toolchains",
      "Cross-Compilation Basics",
      "Final Project: Multithreaded HTTP Server"
    ]
  },

  // ═══════════════════════ Python ═══════════════════════
  {
    id: "python-1", lang: "Python", level: 1,
    color: "#3776AB", bg: "rgba(55,118,171,0.12)", tag: "PY",
    title: "Python Essentials",
    desc: "Learn Python from scratch — syntax, data structures, file handling, and scripting.",
    topics: ["Syntax", "Data Structures", "Functions", "File I/O", "Modules"],
    hours: 25, projects: 6,
    curriculum: [
      "Installing Python & IDE Setup (VS Code / PyCharm)",
      "Variables, Numbers & Strings",
      "String Methods & f-Strings",
      "Lists, Tuples & Sets",
      "Dictionaries & Comprehensions",
      "Conditional Logic & Ternary Operators",
      "Loops: for, while, enumerate, zip",
      "Functions: args, kwargs & Unpacking",
      "Lambda Functions & map/filter/reduce",
      "File I/O: Reading, Writing, CSV",
      "Error Handling: try/except/finally",
      "Modules & Packages (pip)",
      "Virtual Environments & requirements.txt",
      "Basic Scripting & Automation",
      "Final Project: CLI Task Manager"
    ]
  },
  {
    id: "python-2", lang: "Python", level: 2,
    color: "#3776AB", bg: "rgba(55,118,171,0.12)", tag: "PY",
    title: "OOP & Design Patterns",
    desc: "Master object-oriented Python with classes, decorators, and common design patterns.",
    topics: ["Classes", "Decorators", "Generators", "Design Patterns", "Testing"],
    hours: 30, projects: 5,
    curriculum: [
      "Classes & Instances",
      "Dunder Methods (__init__, __repr__, __eq__)",
      "Inheritance & MRO",
      "Abstract Base Classes (ABC)",
      "Properties & Descriptors",
      "Decorators: Functions & Classes",
      "Context Managers (__enter__ / __exit__)",
      "Generators & Iterators",
      "Dataclasses & NamedTuples",
      "Singleton, Factory & Observer Patterns",
      "Strategy & Adapter Patterns",
      "Type Hints & mypy",
      "Unit Testing with pytest",
      "Mocking & Fixtures",
      "Final Project: Plugin-Based CLI Framework"
    ]
  },
  {
    id: "python-3", lang: "Python", level: 3,
    color: "#3776AB", bg: "rgba(55,118,171,0.12)", tag: "PY",
    title: "Data Science with Python",
    desc: "Analyze and visualize data with NumPy, Pandas, Matplotlib, and real-world datasets.",
    topics: ["NumPy", "Pandas", "Matplotlib", "Seaborn", "Data Cleaning"],
    hours: 40, projects: 6,
    curriculum: [
      "NumPy: Arrays, Broadcasting & Vectorization",
      "Advanced Indexing & Slicing",
      "Linear Algebra with NumPy",
      "Pandas: Series & DataFrames",
      "Data Loading: CSV, Excel, JSON, SQL",
      "Indexing: loc, iloc & Boolean Masking",
      "GroupBy, Pivot Tables & Aggregation",
      "Handling Missing Data & Duplicates",
      "Merging, Joining & Concatenation",
      "Matplotlib: Figures, Axes & Subplots",
      "Seaborn: Statistical Visualization",
      "Time Series Analysis Basics",
      "Exploratory Data Analysis (EDA) Workflow",
      "Feature Engineering Fundamentals",
      "Final Project: COVID-19 Data Dashboard"
    ]
  },
  {
    id: "python-4", lang: "Python", level: 4,
    color: "#3776AB", bg: "rgba(55,118,171,0.12)", tag: "PY",
    title: "Machine Learning",
    desc: "Build predictive models with scikit-learn — regression, classification, clustering, and evaluation.",
    topics: ["Scikit-Learn", "Regression", "Classification", "Clustering", "Model Evaluation"],
    hours: 45, projects: 5,
    curriculum: [
      "ML Workflow: Problem → Data → Model → Evaluate",
      "Train/Test Split & Cross-Validation",
      "Linear & Polynomial Regression",
      "Logistic Regression & Decision Boundaries",
      "Decision Trees & Random Forests",
      "Support Vector Machines (SVM)",
      "K-Nearest Neighbors (KNN)",
      "K-Means & DBSCAN Clustering",
      "Dimensionality Reduction: PCA & t-SNE",
      "Feature Selection & Pipeline API",
      "Metrics: Accuracy, Precision, Recall, F1, ROC-AUC",
      "Hyperparameter Tuning: Grid & Random Search",
      "Ensemble Methods: Bagging & Boosting (XGBoost)",
      "Model Serialization with joblib",
      "Final Project: House Price Prediction Pipeline"
    ]
  },
  {
    id: "python-5", lang: "Python", level: 5,
    color: "#3776AB", bg: "rgba(55,118,171,0.12)", tag: "PY",
    title: "Deep Learning & AI",
    desc: "Neural networks with TensorFlow & PyTorch — CNNs, RNNs, Transformers, and deployment.",
    topics: ["TensorFlow", "PyTorch", "CNNs", "RNNs", "Transformers"],
    hours: 50, projects: 4,
    curriculum: [
      "Neural Network Fundamentals & Backpropagation",
      "TensorFlow / Keras: Sequential & Functional API",
      "PyTorch: Tensors, Autograd & nn.Module",
      "Convolutional Neural Networks (CNNs)",
      "Transfer Learning: ResNet, EfficientNet",
      "Data Augmentation & Regularization",
      "Recurrent Networks: LSTM & GRU",
      "Sequence-to-Sequence Models",
      "Attention Mechanism & Transformers",
      "Hugging Face: Pretrained NLP Models",
      "Generative Models: VAE & GAN Basics",
      "Training at Scale: Mixed Precision & Multi-GPU",
      "Model Deployment: ONNX & TF Serving",
      "MLOps: Experiment Tracking with MLflow",
      "Final Project: Image Classifier with Web API"
    ]
  },

  // ═══════════════════════ JavaScript ═══════════════════════
  {
    id: "js-1", lang: "JavaScript", level: 1,
    color: "#F7DF1E", bg: "rgba(247,223,30,0.10)", tag: "JS",
    title: "JavaScript Fundamentals",
    desc: "Core JavaScript — variables, DOM manipulation, events, and ES6+ syntax.",
    topics: ["ES6+ Syntax", "DOM", "Events", "Arrays", "Objects"],
    hours: 28, projects: 6,
    curriculum: [
      "Variables: var, let, const & Hoisting",
      "Data Types & Type Coercion",
      "Strings: Template Literals & Methods",
      "Arrays: Methods (map, filter, reduce, find)",
      "Objects: Destructuring & Spread/Rest",
      "Functions: Arrow, Closures & IIFE",
      "Control Flow & Ternary Operators",
      "DOM Selection & Manipulation",
      "Event Handling & Delegation",
      "Forms: Validation & FormData",
      "Local Storage & Session Storage",
      "ES6 Modules: import / export",
      "Error Handling: try/catch & Custom Errors",
      "Basic Debugging with DevTools",
      "Final Project: Interactive Quiz App"
    ]
  },
  {
    id: "js-2", lang: "JavaScript", level: 2,
    color: "#F7DF1E", bg: "rgba(247,223,30,0.10)", tag: "JS",
    title: "Async JS & APIs",
    desc: "Asynchronous programming — Promises, async/await, Fetch API, and real-world integrations.",
    topics: ["Promises", "Async/Await", "Fetch API", "REST APIs", "Error Handling"],
    hours: 30, projects: 5,
    curriculum: [
      "The Event Loop & Call Stack",
      "Callbacks & Callback Hell",
      "Promises: then, catch, finally",
      "Promise.all, Promise.race & Promise.allSettled",
      "Async / Await Syntax",
      "Fetch API: GET, POST, PUT, DELETE",
      "Working with JSON & Headers",
      "RESTful API Design Principles",
      "Authentication: API Keys & Bearer Tokens",
      "Pagination & Infinite Scroll",
      "AbortController & Request Cancellation",
      "Error Handling Strategies for APIs",
      "Web Workers for Heavy Computation",
      "Intro to WebSockets",
      "Final Project: Weather Dashboard with API"
    ]
  },
  {
    id: "js-3", lang: "JavaScript", level: 3,
    color: "#F7DF1E", bg: "rgba(247,223,30,0.10)", tag: "JS",
    title: "React Development",
    desc: "Build modern UIs with React — components, hooks, state management, and routing.",
    topics: ["Components", "Hooks", "Context API", "React Router", "State Management"],
    hours: 40, projects: 5,
    curriculum: [
      "React Fundamentals & JSX",
      "Components: Functional & Props",
      "State with useState & useReducer",
      "Side Effects with useEffect",
      "Custom Hooks & Reusability",
      "Context API & Global State",
      "React Router v6: Routes & Navigation",
      "Forms: Controlled Components & Validation",
      "Lists, Keys & Conditional Rendering",
      "Performance: React.memo, useMemo, useCallback",
      "Styling: CSS Modules & Styled Components",
      "Data Fetching with React Query / SWR",
      "Testing: React Testing Library & Jest",
      "Accessibility (a11y) in React",
      "Final Project: E-Commerce Product Catalog"
    ]
  },
  {
    id: "js-4", lang: "JavaScript", level: 4,
    color: "#F7DF1E", bg: "rgba(247,223,30,0.10)", tag: "JS",
    title: "Node.js & Backend",
    desc: "Server-side JavaScript — Express, databases, authentication, and REST API development.",
    topics: ["Node.js", "Express", "MongoDB", "Auth", "REST APIs"],
    hours: 40, projects: 5,
    curriculum: [
      "Node.js Runtime & Module System",
      "npm & Package Management",
      "Express.js: Routing & Middleware",
      "Request / Response Lifecycle",
      "RESTful API Design & CRUD",
      "MongoDB & Mongoose ODM",
      "Data Validation with Joi / Zod",
      "Authentication: JWT & bcrypt",
      "Authorization & Role-Based Access",
      "File Uploads with Multer",
      "Error Handling Middleware & Logging",
      "Rate Limiting & Security (Helmet, CORS)",
      "Sending Emails with Nodemailer",
      "Deployment: PM2, Docker Basics",
      "Final Project: Blog API with Auth & CRUD"
    ]
  },
  {
    id: "js-5", lang: "JavaScript", level: 5,
    color: "#F7DF1E", bg: "rgba(247,223,30,0.10)", tag: "JS",
    title: "Full-Stack Next.js & TypeScript",
    desc: "Production-ready apps with Next.js, TypeScript, Prisma, and deployment strategies.",
    topics: ["Next.js", "TypeScript", "Prisma", "SSR/SSG", "Deployment"],
    hours: 50, projects: 4,
    curriculum: [
      "TypeScript Essentials: Types, Interfaces, Generics",
      "Next.js App Router & File-Based Routing",
      "Server Components vs Client Components",
      "Data Fetching: SSR, SSG & ISR",
      "API Routes & Server Actions",
      "Prisma ORM: Schema, Migrations & Queries",
      "Authentication with NextAuth.js",
      "State Management with Zustand",
      "Form Handling with React Hook Form & Zod",
      "Responsive Design & Tailwind CSS",
      "Image Optimization & Lazy Loading",
      "SEO & Metadata API",
      "Testing: Playwright E2E Tests",
      "Deployment: Vercel, CI/CD Pipeline",
      "Final Project: SaaS Dashboard with Stripe"
    ]
  },

  // ═══════════════════════ Rust ═══════════════════════
  {
    id: "rust-1", lang: "Rust", level: 1,
    color: "#CE422B", bg: "rgba(206,66,43,0.12)", tag: "RS",
    title: "Rust Foundations",
    desc: "Learn Rust's unique ownership model, types, pattern matching, and safe memory management.",
    topics: ["Ownership", "Borrowing", "Structs", "Enums", "Pattern Matching"],
    hours: 35, projects: 5,
    curriculum: [
      "Installing Rust & Cargo Basics",
      "Variables, Mutability & Shadowing",
      "Scalar & Compound Types",
      "Functions & Control Flow",
      "Ownership & the Borrow Checker",
      "References & Borrowing Rules",
      "Slices: String & Array Slices",
      "Structs & Methods (impl blocks)",
      "Enums & Option<T>",
      "Pattern Matching with match & if let",
      "Vectors, Strings & HashMaps",
      "Error Handling: Result<T, E> & ? Operator",
      "Modules, Crates & Cargo Workspaces",
      "Traits & Generics Introduction",
      "Final Project: CLI File Search Tool"
    ]
  },
  {
    id: "rust-2", lang: "Rust", level: 2,
    color: "#CE422B", bg: "rgba(206,66,43,0.12)", tag: "RS",
    title: "Rust Error Handling & Traits",
    desc: "Advanced traits, generics, lifetimes, iterators, and robust error handling strategies.",
    topics: ["Lifetimes", "Trait Bounds", "Iterators", "Closures", "Error Design"],
    hours: 35, projects: 4,
    curriculum: [
      "Trait Objects & Dynamic Dispatch (dyn Trait)",
      "Generics with Trait Bounds",
      "Lifetime Annotations & Elision Rules",
      "Closures: Fn, FnMut, FnOnce",
      "Iterators: map, filter, collect, fold",
      "Custom Iterator Implementations",
      "The From / Into Traits",
      "Custom Error Types with thiserror",
      "Error Propagation Patterns",
      "Smart Pointers: Box, Rc, Arc",
      "Interior Mutability: Cell & RefCell",
      "Deref & Drop Traits",
      "Testing: Unit, Integration & Doc Tests",
      "Cargo Features & Conditional Compilation",
      "Final Project: Markdown Parser Library"
    ]
  },
  {
    id: "rust-3", lang: "Rust", level: 3,
    color: "#CE422B", bg: "rgba(206,66,43,0.12)", tag: "RS",
    title: "Systems & Concurrency",
    desc: "Fearless concurrency, async Rust with Tokio, unsafe code, and systems-level programming.",
    topics: ["Concurrency", "Async/Await", "Tokio", "Unsafe", "FFI"],
    hours: 40, projects: 4,
    curriculum: [
      "Threads & std::thread",
      "Message Passing with Channels (mpsc)",
      "Shared State: Mutex<T> & RwLock<T>",
      "Arc<Mutex<T>> for Thread-Safe Sharing",
      "Send & Sync Traits",
      "Async / Await Fundamentals",
      "Tokio Runtime & Task Spawning",
      "Async I/O: Files & Networking",
      "Building an Async HTTP Client",
      "Unsafe Rust: Raw Pointers & FFI",
      "Calling C from Rust & vice versa",
      "Procedural Macros Basics",
      "Performance Profiling & Benchmarking",
      "Cross-Compilation & WASM Targets",
      "Final Project: Concurrent Web Scraper with Tokio"
    ]
  },

  // ═══════════════════════ Java ═══════════════════════
  {
    id: "java-1", lang: "Java", level: 1,
    color: "#ED8B00", bg: "rgba(237,139,0,0.12)", tag: "JV",
    title: "Java Fundamentals",
    desc: "Core Java — OOP principles, collections, exception handling, and the JVM ecosystem.",
    topics: ["OOP", "Collections", "Exceptions", "Generics", "JVM"],
    hours: 35, projects: 6,
    curriculum: [
      "JDK Setup & IDE Configuration (IntelliJ / Eclipse)",
      "Variables, Data Types & Operators",
      "Control Flow: if/else, switch, loops",
      "Methods: Overloading & Variable Arguments",
      "Classes, Objects & Constructors",
      "Encapsulation: Getters/Setters & Access Modifiers",
      "Inheritance & the super Keyword",
      "Polymorphism & Method Overriding",
      "Abstract Classes & Interfaces",
      "Exception Handling: try/catch/finally, Custom Exceptions",
      "Collections: List, Set, Map & Queue",
      "Generics & Wildcards",
      "String Handling & StringBuilder",
      "File I/O with java.nio",
      "Final Project: Library Management System"
    ]
  },
  {
    id: "java-2", lang: "Java", level: 2,
    color: "#ED8B00", bg: "rgba(237,139,0,0.12)", tag: "JV",
    title: "Streams, Lambdas & Modern Java",
    desc: "Functional programming in Java — lambdas, streams, Optional, and modern Java features.",
    topics: ["Lambdas", "Streams API", "Optional", "Records", "Sealed Classes"],
    hours: 30, projects: 4,
    curriculum: [
      "Functional Interfaces & @FunctionalInterface",
      "Lambda Expressions & Method References",
      "Stream API: map, filter, reduce, collect",
      "Parallel Streams & Performance",
      "Optional<T>: Safe Null Handling",
      "Collectors: groupingBy, partitioning, toMap",
      "Records & Compact Constructors",
      "Sealed Classes & Pattern Matching",
      "Text Blocks & String Templates",
      "Switch Expressions & Pattern Matching",
      "var (Local Variable Type Inference)",
      "Immutable Collections (List.of, Map.of)",
      "CompletableFuture & Async Programming",
      "Modules (Java Platform Module System)",
      "Final Project: Data Analytics Pipeline"
    ]
  },
  {
    id: "java-3", lang: "Java", level: 3,
    color: "#ED8B00", bg: "rgba(237,139,0,0.12)", tag: "JV",
    title: "Spring Boot & REST APIs",
    desc: "Build production-grade REST APIs with Spring Boot, JPA, security, and deployment.",
    topics: ["Spring Boot", "JPA/Hibernate", "Spring Security", "REST", "Docker"],
    hours: 45, projects: 4,
    curriculum: [
      "Spring Boot: Auto-Configuration & Starters",
      "Project Structure & Application Properties",
      "REST Controllers & Request Mapping",
      "Request/Response: DTOs & Validation",
      "Service Layer & Dependency Injection",
      "Spring Data JPA & Hibernate",
      "Entity Relationships: OneToMany, ManyToMany",
      "Pagination, Sorting & Specifications",
      "Exception Handling with @ControllerAdvice",
      "Spring Security: JWT Authentication",
      "Role-Based Authorization",
      "API Documentation with SpringDoc / Swagger",
      "Unit & Integration Testing (MockMvc, Testcontainers)",
      "Dockerizing Spring Boot Applications",
      "Final Project: E-Commerce REST API"
    ]
  },

  // ═══════════════════════ SQL ═══════════════════════
  {
    id: "sql-1", lang: "SQL", level: 1,
    color: "#336791", bg: "rgba(51,103,145,0.12)", tag: "SQL",
    title: "SQL Fundamentals",
    desc: "Relational databases from scratch — queries, joins, aggregation, and subqueries.",
    topics: ["SELECT", "JOINs", "Aggregation", "Subqueries", "DDL"],
    hours: 22, projects: 5,
    curriculum: [
      "Relational Database Concepts & RDBMS Setup",
      "CREATE TABLE, INSERT, UPDATE, DELETE",
      "SELECT: Filtering with WHERE & LIKE",
      "Sorting & Limiting Results (ORDER BY, LIMIT)",
      "Aggregate Functions: COUNT, SUM, AVG, MIN, MAX",
      "GROUP BY & HAVING Clauses",
      "INNER JOIN & OUTER JOINs (LEFT, RIGHT, FULL)",
      "Self Joins & Cross Joins",
      "Subqueries: Scalar, Row & Table Subqueries",
      "UNION, INTERSECT & EXCEPT",
      "Data Types & Constraints (PK, FK, UNIQUE, CHECK)",
      "ALTER TABLE & Schema Migrations",
      "Views & Materialized Views",
      "Basic Transactions: BEGIN, COMMIT, ROLLBACK",
      "Final Project: Employee Management Queries"
    ]
  },
  {
    id: "sql-2", lang: "SQL", level: 2,
    color: "#336791", bg: "rgba(51,103,145,0.12)", tag: "SQL",
    title: "Performance & Database Design",
    desc: "Advanced SQL — indexing, query optimization, normalization, and stored procedures.",
    topics: ["Indexing", "Query Plans", "Normalization", "Stored Procedures", "CTEs"],
    hours: 28, projects: 4,
    curriculum: [
      "Common Table Expressions (CTEs) & Recursive CTEs",
      "Window Functions: ROW_NUMBER, RANK, LEAD, LAG",
      "PARTITION BY & Frame Specifications",
      "Indexing Strategies: B-Tree, Hash & Composite Indexes",
      "EXPLAIN / ANALYZE: Reading Query Plans",
      "Query Optimization Techniques",
      "Normalization: 1NF → 2NF → 3NF → BCNF",
      "Denormalization for Read Performance",
      "Stored Procedures & Functions",
      "Triggers & Event-Driven Logic",
      "Transactions: Isolation Levels & Locking",
      "Database Security: GRANT, REVOKE & Row-Level Security",
      "JSON & Array Data Types (PostgreSQL)",
      "Partitioning & Sharding Concepts",
      "Final Project: E-Commerce Database Design & Optimization"
    ]
  }
];
